# Site settings
title: Syed Hussain Ather
name: Syed Hussain Ather

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Personal Website
   url: http://hussainather.com
 - title: Facebook
   url: https://www.facebook.com/shussainather
 - title: GitHub
   url: https://github.com/hussainther
 - title: LinkedIn
   url: https://www.linkedin.com/in/syed-hussain-ather-049919137/
 - title: Medium
   url: https://medium.com/@HussainAther
 - title: Twitch
   url: https://www.twitch.tv/hussainather
 - title: Twitter
   url: https://twitter.com/sHussainAther

skills:
 - Python
 - R
 - C
 - MATLAB
 - data Science
 - machine learning
 - software engineering
 - bioinformatics
 - fMRI
 - physics
 - mathematics
 - philosophy
 - biology
 - neuroscience
 - computer science
 - writing

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://hussainather.com/feed/json

#Work experience is required
roles:
 - title: Post-baccalureate Researcher
   start: 2017
   end: 2019
   employer: National Institutes of Health
   description: Created a Snakemake workflow for performing ChIP-Seq, RNA-Seq differential splicing, and colocalization analysis from FASTQ files through called peaks which is run in parallel on NIH’s Biowulf cluster. Performed Fisher’s exact test and Jaccard index in detecting colocalization events. Used deeptools and bedtools in determining the differences between peak-callers. Detected and fixed errors in PeakSeg supervised peak-calling algorithm. Visualized output from ChIP-Seq peak-calling algorithms to understand their differences in terms of biases, underlying assumptions, and applicability to particular datasets. Manually created labels of peak-calling output for learning a model to optimize ChIP-Seq peak-callers. Lead a group of researchers to create SeqAcademy.org, a self-guided educational tutorial for RNA-Seq and ChIP-Seq analysis. Used machine learning methods, including exploratory data analysis and feature engineering, with the goal of creating a publishable tool to decide which parameters should be used on a particular dataset.
 - title: Undergraduate Research Intern
   start: 2015
   end: 2015
   employer: Conte Center for Computational Neuropsychiatric Genomics
   description: Performed RNA-Seq analysis using STAR aligner to analyze genetic expression for significantly expressed genes in the human brain. Updated human brain transcriptome from long reads of PacBio Iso-Seq data. Used differential equations and graphs to visualize new isoforms uncovered.
 - title: Undergraduate Research Intern
   start: 2014
   end: 2014
   employer: Boyce Thompson Institute
   description: Performed RNA-Seqanalysis using Tuxedo suite on tomatoes to extract genetic information. Explored mechanisms behind transcription and protein synthesis.
– Implemented novel algorithms to optimize run-times of virus detection software.
 - title: Undergraduate Research Assistant
   start: 2013
   end: 2017
   employer: Indiana University-Bloomington
   description: Engineered software for constructed gene trees reconciled with MUL-trees to identify and resolve polyploidy events in simulated organisms; parallelized pipeline to increase effectiveness of heavy-input reconciliations. Compared the effectiveness of whole-genome alignment methods in detecting indel mutations. Created algorithms for bioinformatics solutions including sorting, searching, and performing operations on biological data such as splice junctions, de Brujin graphs, and RNA strings. Summarized and discussed implications and methods of research papers during meetings. Created Pac-Man game that eats DNA bases and produces strings of amino acids.

#Education is required
education:
 - level: Postbaccalaureate
   date: 2019
   subject: Interdisciplinary
   school: Foundation for Advanced Education in the Sciences Graduate School at the National Institutes of Health
 - level: Bachelor of Arts (B.A.)
   date: 2017
   subject: Physics
   school: Indiana University-Bloomington

#List of interesting Github repo/projects to include - optional
github:
 - hussainther/physics
 - hussainther/mathematics
 - hussainther/philosophy
 - hussainther/computerscience
 - hussainther/neuroscience
 - hussainther/biology
 - hussainther/journalism
 - NCBI-Hackathons/seqacademy

intro: |
  I am a researcher-writer in neurosicence and philosophy. I strive to take a quantitative approach to researching to the natural world. Through mathematical, quantitiative, and computational approaches, I hope to create a greater understanding of the computational theory of mind through research that can give rise to revolutionary, innovative theories.
  As Immanuel Kant said, studying concepts of the mind without empirical science is empty and studying science without philosophy is blind. As an undergraduate, I studied physics and philosophy. This prepared me for taking many different approaches to thinking about problems as well as understanding the basics of philosophy of science that underlie computational neuroscience research. 
  This has given me an understanding of theories of connectionism, classicalism, and other philosophical ideas relevant to neuroscience as well as how research in the philosophy of mind reflects findings in neuroscience. I want to continue to engage in the history and philosophy of computational neuroscience by, for example, critiquing the cybernetic idealism that Warren McCulloch and 
  Walter Pitts first described in the 1940 or the representations of AI as symbolic or connectionist over the past century. 

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Python</strong>: I primarily use python for most of my programming including data extraction, visualization, and software engineering.<br/><br/>
   <strong>R</strong>: I have used R for statistics, machine learning, and data science techniques in situations where R is more efficient or effective than Python. <br/><br/>
   <strong>MATLAB</strong> I have used MATLAB for computation-heavy procedures in neuroscience as they benefit the field of computational neuroscience for giving reserachers new tools to study empirical data. <br/><br/>
   <strong>Haskell</strong>: I have used Haskell to understand programming language theory and perform mathematical computations on large sets of dat.<br/><br/>
   <strong>Data Science</strong>: Through these approahces to understand the mathematics, physics, and computer science of biology and neuroscience, I have performed data science techniques and critiqued methods as they relate to artificial intelilgence, machine learning, and other digital philosophy.<br/><br/>
   <strong>Software Engineering</strong>: I have a good knowledge of creating applications and similar files for software in bioinformatics and computational neuroscience.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including C and programming contests through Rosalind.<br/><br/>
